apiVersion: batch/v1
kind: Job
metadata:
  generateName: gh-action-trigger-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: gh-action-trigger
        image: curlimages/curl
        command:
          - "curl"
          - "-L"
          - "-X"
          - "POST"
          - "-H"
          - "Accept: application/vnd.github+json"
          - "-H"
          - "Authorization: Bearer ${GITHUB_TOKEN}"
          - "-H"
          - "X-Github-Api-Version: 2022-11-28"
          - "https://xxxxx"
          - "--data"
          - "'{\"event_type\": \"do-something\"}'"
        envFrom:
        - secretRef:
            name: github-token
      restartPolicy: Never
  backoffLimit: 2
