apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-demo-app
  namespace: argocd
spec:
  destination:
    namespace: prod 
    server: 'https://kubernetes.default.svc'
  sources:
    - chart: helm-demo-app-chart
      repoURL: 352858358668.dkr.ecr.us-east-1.amazonaws.com
      targetRevision: 0.1.1
      helm:
        valueFiles:
          - $values/values-prod.yaml
        parameters:
          - name: image.repo
            value: $ARGOCD_APP_SOURCE_REPO_URL
    - repoURL: 'https://github.com/candonov/demo-app.git'
      targetRevision: HEAD
      ref: values
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
