apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-demo-app
  namespace: argocd
spec:
  destination:
    namespace: prod 
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: 'https://github.com/candonov/demo-app.git'
      targetRevision: HEAD
      path: chart/demo-app/
      helm:
        valueFiles:
          - $values/values-prod.yaml
    - repoURL: 'https://github.com/candonov/demo-app.git'
      targetRevision: HEAD
      ref: values
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
