name: Deploy to Prod

on:
  push:
    branches:
      - main
    paths:
      - 'values-prod.yaml'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  builds:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    steps:  
    - name: Jira Login
      uses: atlassian/gajira-login@v3
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        
    - name: checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - uses: actions-ecosystem/action-get-latest-tag@v1
      id: get-latest-tag
      
    - id: find-issue
      name: Find in commit messages
      uses: atlassian/gajira-find-issue-key@v3
      with:
        string: ${{ github.event.head_commit.message }}
        
    - name: Comment on issue
      uses: atlassian/gajira-comment@v3
      with:
        issue: ${{ steps.find-issue.outputs.issue }}
        comment: ${{ github.event.pusher.name }} deployed version ${{ steps.release.outputs.tag_name }} to prod
        
    - name: Transition issue to Done
      id: transition
      uses: atlassian/gajira-transition@v3
      with:
        issue: ${{ steps.find-issue.outputs.issue }}
        transition: "Done"

